packages:
  - "apps/*"
  - "packages/*"

ignoredBuiltDependencies:
  - esbuild
  - electron-winstaller

allowBuilds:
  electron-winstaller: set this to true or false
  electron@41.10.7: true

strictDepBuilds: false
