// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function AppendSessionEvent(arg1:domain.AppendEventRequest):Promise<domain.SessionEvent>;

export function ApprovePermissionRequest(arg1:domain.ApprovePermissionRequestInput):Promise<domain.PermissionRequest>;

export function ArchiveSession(arg1:string):Promise<domain.Session>;

export function BuildSessionContext(arg1:domain.BuildSessionContextRequest):Promise<domain.BuildSessionContextResult>;

export function CancelProviderAuth(arg1:string):Promise<domain.ProviderAuthStatus>;

export function CancelSessionTurn(arg1:domain.CancelTurnRequest):Promise<domain.Turn>;

export function CompleteInitialization(arg1:domain.ProviderConfig):Promise<domain.AppConfig>;

export function CompleteSessionTurn(arg1:domain.CompleteTurnRequest):Promise<domain.Turn>;

export function ConnectProvider(arg1:domain.ProviderConnectInput):Promise<domain.CatalogState>;

export function CreateSession(arg1:domain.CreateSessionRequest):Promise<domain.Session>;

export function CreateSessionCheckpoint(arg1:domain.CreateCheckpointRequest):Promise<domain.SessionCheckpoint>;

export function CreateSessionSummary(arg1:domain.CreateSummaryRequest):Promise<domain.SessionSummary>;

export function DeleteProviderAccount(arg1:string):Promise<domain.CatalogState>;

export function DeleteSession(arg1:string):Promise<domain.Session>;

export function DenyPermissionRequest(arg1:domain.DenyPermissionRequestInput):Promise<domain.PermissionRequest>;

export function FailSessionTurn(arg1:domain.FailTurnRequest):Promise<domain.Turn>;

export function ForkSession(arg1:domain.ForkSessionRequest):Promise<domain.Session>;

export function GetAppConfig():Promise<domain.AppConfig>;

export function GetCodingContext(arg1:string):Promise<domain.CodingContext>;

export function GetLatestSession():Promise<domain.ResumeRecap>;

export function GetLatestSessionByProject(arg1:string):Promise<domain.ResumeRecap>;

export function GetLatestSessionCheckpoint(arg1:string):Promise<domain.SessionCheckpoint>;

export function GetLatestSessionSummary(arg1:string):Promise<domain.SessionSummary>;

export function GetProviderAuthStatus(arg1:string):Promise<domain.ProviderAuthStatus>;

export function GetProviderCatalog():Promise<domain.CatalogState>;

export function GetSession(arg1:string):Promise<domain.Session>;

export function ListPermissionRequests(arg1:string,arg2:string):Promise<Array<domain.PermissionRequest>>;

export function ListSessionCheckpoints(arg1:string,arg2:number):Promise<Array<domain.SessionCheckpoint>>;

export function ListSessionEvents(arg1:string,arg2:boolean,arg3:number):Promise<Array<domain.SessionEvent>>;

export function ListSessionToolCalls(arg1:string):Promise<Array<domain.ToolCall>>;

export function ListSessionTurns(arg1:string,arg2:number):Promise<Array<domain.Turn>>;

export function ListSessions(arg1:domain.ListSessionsRequest):Promise<Array<domain.Session>>;

export function RefreshProviderModels(arg1:domain.ProviderConnectInput):Promise<domain.CatalogState>;

export function ResumeSession(arg1:domain.ResumeSessionRequest):Promise<domain.ResumeRecap>;

export function SaveSessionToolCall(arg1:domain.CreateToolCallRequest):Promise<domain.ToolCall>;

export function SelectProjectDirectory():Promise<string>;

export function StartProviderAuth(arg1:domain.ProviderAuthStartInput):Promise<domain.ProviderAuthStartResult>;

export function StartSessionTurn(arg1:domain.StartTurnRequest):Promise<domain.Turn>;

export function SubmitSessionMessage(arg1:domain.SubmitSessionMessageRequest):Promise<domain.PreparedSessionTurn>;

export function SubmitSessionMessageStreaming(arg1:domain.SubmitSessionMessageRequest):Promise<domain.PreparedSessionTurn>;

export function UpdateCodingContext(arg1:string,arg2:string):Promise<domain.CodingContext>;

export function UpdateModelPreferences(arg1:domain.ModelPreferencesInput):Promise<domain.AppConfig>;

export function UpdateSession(arg1:domain.UpdateSessionRequest):Promise<domain.Session>;
