/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ProjectsChatRouteImport } from './routes/projects.chat'
import { Route as ProjectsExtensionsRouteImport } from './routes/projects.extensions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsChatRoute = ProjectsChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsExtensionsRoute = ProjectsExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/extensions': typeof ExtensionsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/projects/chat': typeof ProjectsChatRoute
  '/projects/extensions': typeof ProjectsExtensionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/extensions': typeof ExtensionsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/projects/chat': typeof ProjectsChatRoute
  '/projects/extensions': typeof ProjectsExtensionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/extensions': typeof ExtensionsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/projects/chat': typeof ProjectsChatRoute
  '/projects/extensions': typeof ProjectsExtensionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/extensions'
    | '/projects'
    | '/prompts'
    | '/settings'
    | '/setup'
    | '/projects/chat'
    | '/projects/extensions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/extensions'
    | '/projects'
    | '/prompts'
    | '/settings'
    | '/setup'
    | '/projects/chat'
    | '/projects/extensions'
  id:
    | '__root__'
    | '/'
    | '/extensions'
    | '/projects'
    | '/prompts'
    | '/settings'
    | '/setup'
    | '/projects/chat'
    | '/projects/extensions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExtensionsRoute: typeof ExtensionsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  PromptsRoute: typeof PromptsRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/chat': {
      id: '/projects/chat'
      path: '/chat'
      fullPath: '/projects/chat'
      preLoaderRoute: typeof ProjectsChatRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/extensions': {
      id: '/projects/extensions'
      path: '/extensions'
      fullPath: '/projects/extensions'
      preLoaderRoute: typeof ProjectsExtensionsRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsChatRoute: typeof ProjectsChatRoute
  ProjectsExtensionsRoute: typeof ProjectsExtensionsRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsChatRoute: ProjectsChatRoute,
  ProjectsExtensionsRoute: ProjectsExtensionsRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExtensionsRoute: ExtensionsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  PromptsRoute: PromptsRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
