import assert from 'node:assert/strict';
import test from 'node:test';
import { extractRequirements, generateTraceabilityMarkdown, parseChangeYamlText } from './document-governance-lib.mjs';

test('extracts Requirement-owned Test IDs without copying acceptance prose', () => {
  const requirements = extractRequirements(`### REQ-ONE-001 First behavior

Acceptance: \`AT-ONE-001\` and \`CT-SHARED-001\`.

### NFR-TWO-001 Second behavior

Acceptance: \`CT-SHARED-001\`.
`);
  assert.deepEqual(requirements, [
    { id: 'REQ-ONE-001', title: 'First behavior', tests: ['AT-ONE-001', 'CT-SHARED-001'] },
    { id: 'NFR-TWO-001', title: 'Second behavior', tests: ['CT-SHARED-001'] },
  ]);
});

test('generates deterministic active and sealed Traceability links', () => {
  const requirementText = `### REQ-ONE-001 First behavior

Acceptance: \`AT-ONE-001\`.
`;
  const changes = [
    { change: { id: 'CHG-2026-001-old', status: 'Verified', requirements: ['REQ-ONE-001'], adrs: ['ADR-0001'] } },
    { change: { id: 'CHG-2026-002-new', status: 'Implementing', requirements: ['REQ-ONE-001'], adrs: ['ADR-0002'] } },
  ];
  const generated = generateTraceabilityMarkdown({ requirementText, changes, archivedIds: new Set(['CHG-2026-001-old']) });
  assert.match(generated, /Generated by `pnpm docs:trace`/);
  assert.match(generated, /ADR-0001, ADR-0002/);
  assert.match(generated, /CHG-2026-002-new.*Implementing/);
  assert.match(generated, /CHG-2026-001-old/);
  assert.equal(generated, generateTraceabilityMarkdown({ requirementText, changes, archivedIds: new Set(['CHG-2026-001-old']) }));
});

test('parses minimal schema-v2 metadata', () => {
  const change = parseChangeYamlText('schema: "2"\nstatus: "Draft"\ngoal: "Preserve a decision"\nrequirements: []\n');
  assert.equal(change.schema, '2');
  assert.equal(change.status, 'Draft');
  assert.deepEqual(change.requirements, []);
});
